### ISSUE TITLE
Account for use case `language` is empty string

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.exportimport#10]
The `plone-exporter` breaks if finds an object that serializes `language: ''`:

```
Traceback (most recent call last):
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/./bin/plone-exporter", line 8, in <module>
    sys.exit(exporter_cli())
             ^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/cli/__init__.py", line 50, in exporter_cli
    results = get_exporter(site).export_site(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/exporters/__init__.py", line 72, in export_site
    paths.extend(exporter.export_data(path))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/exporters/content.py", line 159, in export_data
    return super().export_data(base_path, data_hooks, obj_hooks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/exporters/base.py", line 65, in export_data
    paths = self.dump()
            ^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/exporters/content.py", line 135, in dump
    path = self.dump_one(obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/exporters/content.py", line 116, in dump_one
    data = self.serialize(obj)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/exporters/content.py", line 89, in serialize
    data = fixer.func(data, obj, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sneridagh/Development/kitconcept/kitconcept.com/backend/sources/plone.exportimport/src/plone/exportimport/utils/content/export_helpers.py", line 117, in fix_language
    token = item.get("language", {}).get("token", placeholder)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by ericof** [comment]
Fixed in #12
